LIBEXECDIR should be set and used
OpenBangla/OpenBangla-Keyboard pull request #208
Opened 2021-04-22 05:53 UTC by gunnarhj

The architecture dependent executables ibus-openbangla and
openbangla-gui are currently installed in the /usr/share hierarchy,
which is not in accordance with the Filesystem Hierarchy Standard
for UNIX-like operating systems. This commit moves those files to
the more proper /usr/libexec directory.

2021-04-22 07:18 UTC, mominul commented
Thanks! But this issue was already raised in #183 and I resolved this in #206. Can you check that out, please? If that doesn't suffice, I'd be happy to merge this PR.

2021-04-22 07:51 UTC, gunnarhj commented
Ah, I didn't notice that you have multiple branches. Now I see it in `develop_initial`.

I still think `/usr/libexec` is more appropriate in this case than `/usr/bin`. The latter is in `PATH` and intended for user commands, and Debian's checks will complain about missing man pages. ;-) (But that is a less important thing.)

Whatever you decide, I think you should change `src/engine/ibus/main.cpp` too.

2021-04-22 08:34 UTC, gunnarhj commented
You may want to check out [this Debian bug](https://bugs.debian.org/955219). openbangla-keyboard would divert (at least in Debian) with `/usr/bin` compared to other IBus input methods.

2021-04-22 10:33 UTC, mominul commented
> You may want to check out this Debian bug.

That's tricky. The [Arch Package Guidelines](https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_etiquette) however insists to avoid `/usr/libexec/` directory but the FHS 3.0 standard advocates for it. :disappointed: Maybe the guidelines need to be updated?

2021-04-22 11:24 UTC, gunnarhj commented
Please note that Arch says:

> Avoid using `/usr/libexec/` for anything. Use `/usr/lib/$pkgname/` instead.

Neither Arch nor FHS 3.0 mentions `/usr/bin`, so at least they seem to agree that that is not correct.

Most IBus plugins default to `/usr/libexec`. Debian/Ubuntu previously changed it (typically via a `--libexec-dir` configure flag) to `/usr/lib/ibus` since IBus couldn't cope with `/usr/libexec` (in some respect I don't remember). That was changed in Debian's version 1.5.22-2 of ibus — hence that bug report.

2021-04-22 12:10 UTC, ahmubashshir commented
AFAIK, arch insists packagers to use `/usr/lib/ibus-<package>`, so I think it'd be better to use `/usr/lib/ibus-openbangla`.

2021-04-22 17:23 UTC, mominul commented
> Neither Arch nor FHS 3.0 mentions `/usr/bin`, so at least they seem to agree that that is not correct.

I am fine with not placing the binaries in the `/usr/bin`. I just had the confusion about choosing between `/usr/libexec` or `/usr/lib/ibus` directory.

> Maybe make `LIBEXECDIR` configurable. And let it default to either /usr/libexec (my choice) or /usr/lib/ibus.

Yeah, it seems the best possible solution for now. :+1: 

But `openbangla-gui` is a user-facing application that has also a desktop entry, where should we place this binary?

> I prefer /usr/lib/openbangla-keyboard.

As we're trying to follow the convention of other ibus engines, I don't think placing the engine binary in that directory would be good. But placing `openbangla-gui` there is plausible and need decision.

2021-04-22 17:39 UTC, ahmubashshir commented
ibus-openbangla -> /usr/lib/openbangla-keyboard/ibus-openbangla
openbangla-gui -> /usr/bin/openbangla-gui
	Mubashshir

On Thu, Apr 22, 2021 at 10:23, Muhammad Mominul Huque 
***@***.***> wrote:
>> Neither Arch nor FHS 3.0 mentions /usr/bin, so at least they seem to 
>> agree that that is not correct.
>> 
> I am fine with not placing the binaries in the /usr/bin. I just had 
> the confusion about choosing between /usr/libexec or /usr/lib/ibus 
> directory.
> 
>> Maybe make LIBEXECDIR configurable. And let it default to either 
>> /usr/libexec (my choice) or /usr/lib/ibus.
>> 
> Yeah, it seems the best possible solution for now. 👍
> 
> But openbangla-gui is a user-facing application that has also a 
> desktop entry, where should we place this binary?
> 
>> I prefer /usr/lib/openbangla-keyboard.
>> 
> As we're trying to follow the convention of other ibus engines, I 
> don't think placing the engine binary in that directory would be 
> good. But placing openbangla-gui there is plausible and need decision.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/OpenBangla/OpenBangla-Keyboard/pull/208#issuecomment-825042837>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AF5WM3WEGVMMFQA6P55XQO3TKBLR7ANCNFSM43LXNZLQ>.
>

2021-04-22 23:44 UTC, gunnarhj commented
@mominul wrote:
> As we're trying to follow the convention of other ibus engines

Re how others do, there is a pattern — also with respect to the file names:

```
$ ls -1 /usr/libexec/ibus-* | grep -E 'engine|setup'
/usr/libexec/ibus-engine-anthy
/usr/libexec/ibus-engine-hangul
/usr/libexec/ibus-engine-libpinyin
/usr/libexec/ibus-engine-libthai
/usr/libexec/ibus-engine-m17n
/usr/libexec/ibus-engine-simple
/usr/libexec/ibus-engine-table
/usr/libexec/ibus-engine-unikey
/usr/libexec/ibus-setup-anthy
/usr/libexec/ibus-setup-hangul
/usr/libexec/ibus-setup-libpinyin
/usr/libexec/ibus-setup-libthai
/usr/libexec/ibus-setup-m17n
/usr/libexec/ibus-setup-table
/usr/libexec/ibus-setup-unikey
```

2021-04-24 11:22 UTC, mominul commented
@gunnarhj `openbangla-gui` is a user-facing application that has also a desktop entry, where should we place this binary?

2021-04-24 18:40 UTC, ahmubashshir commented
`openbangla-gui` should be in `/usr/bin/`

2021-04-24 20:45 UTC, gunnarhj commented
@mominul wrote:
> `openbangla-gui` is a user-facing application that has also a desktop entry, where should we place this binary?

If I understand it correctly, the presence of a `.desktop` file does not in itself change anything. I'm aware of one other IM (mozc) which has a `.desktop` file with a visible icon in the menus, and the location of its equivalent is:

    /usr/lib/mozc/mozc_tool

But mozc is a bit special, since it provides input methods for multiple IM frameworks, i.e. not only ibus.

So I still think that `/usr/libexec` would be a proper location.

@ahmubashshir wrote:
> `openbangla-gui` should be in `/usr/bin/`

Provided that the intention is to make it easy for users to start the thing via a terminal command, that's a proper location. Otherwise `/usr/libexec` is better.

2021-04-27 08:42 UTC, mominul requested changes
Thanks for the inputs @gunnarhj!
Could you please rebase this PR onto the [`develop`](https://github.com/OpenBangla/OpenBangla-Keyboard/tree/develop) and consider adding the requested changes?

Thanks!

2021-04-27 08:42 UTC, mominul commented on src/frontend/CMakeLists.txt
> +        RUNTIME DESTINATION ${LIBEXECDIR})
I'd like to place the `openbangla-gui` binary under the `/usr/lib/openbangla-keyboard` directory. It seems like we'll get a fcitx backend #202 in the future, so let's follow the `mozc` :grin:

2021-04-27 08:42 UTC, mominul commented on data/openbangla-keyboard.desktop.in
> +Exec=@LIBEXECDIR@/openbangla-gui %f
This will need to change as we're considering placing the binary in a different place.

2021-04-27 08:42 UTC, mominul commented on src/engine/ibus/CMakeLists.txt
>  install(TARGETS ibus-openbangla
Let's rename the binary to `ibus-engine-openbangla`.

2021-04-27 08:42 UTC, mominul commented on src/engine/ibus/main.cpp
> +                                   LIBEXECDIR "/ibus-openbangla --ibus",
Will need to change as we're changing the binary name.

2021-04-27 08:42 UTC, mominul commented on data/openbangla.xml.in
> +    <exec>@LIBEXECDIR@/ibus-openbangla --ibus</exec>
Will need to change as we're changing the binary name.

2021-04-27 08:43 UTC, mominul commented
cc @natrys

2021-04-27 15:09 UTC, gunnarhj commented
Ok @mominul, I think I have changed it in accordance with your comments, at least almost...

I put `openbangla-gui` in `/usr/libexec/openbangla-keyboard` instead of `/usr/lib/openbangla-keyboard` to be consistent and avoid the addition of yet another variable.

I'm not a git wizard, so instead of rebasing I simply force pushed the modified branch.

2021-04-29 05:25 UTC, mominul approved these changes
Thanks!

2021-04-29 05:26 UTC, merged